plugins {
    id 'com.gradleup.shadow'
}

architectury {
    platformSetupLoomIde()
    neoForge()
}

configurations {
    common {
        canBeResolved = true
        canBeConsumed = false
    }
    compileClasspath.extendsFrom common
    runtimeClasspath.extendsFrom common
    developmentNeoForge.extendsFrom common

    // Files in this configuration will be bundled into your mod using the Shadow plugin.
    // Don't use the `shadow` configuration from the plugin itself as it's meant for excluding files.
    shadowBundle {
        canBeResolved = true
        canBeConsumed = false
    }
}

repositories {
    maven {
        name = 'NeoForged'
        url = 'https://maven.neoforged.net/releases'
    }
    // currently no version available for 26.2
	// maven { url = "https://maven.createmod.net" } // Create, Ponder, Flywheel
    // maven { url = "https://maven.ithundxr.dev/snapshots" } // Registrate
}

dependencies {
    neoForge "net.neoforged:neoforge:$rootProject.neoforge_version"

    common(project(path: ':common')) { transitive false }
    shadowBundle project(path: ':common', configuration: 'transformProductionNeoForge')
	
    // currently no version available for 26.2
	// implementation("com.simibubi.create:create-${minecraft_version}:${create_version}:slim") { transitive = false }
    // implementation("net.createmod.ponder:Ponder-NeoForge-${minecraft_version}:${ponder_version}")
    // compileOnly("dev.engine-room.flywheel:flywheel-neoforge-api-${minecraft_version}:${flywheel_version}")
    // runtimeOnly("dev.engine-room.flywheel:flywheel-neoforge-${minecraft_version}:${flywheel_version}")
    // implementation("com.tterrag.registrate:Registrate:${registrate_version}")
}

processResources {
    inputs.property 'version', project.version

    filesMatching('META-INF/neoforge.mods.toml') {
        expand version: project.version
    }
}

shadowJar {
    configurations = [project.configurations.shadowBundle]
    archiveClassifier = 'dev-shadow'
}